// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: managed_charging.proto
// Protobuf Java Version: 4.31.1

package ManagedCharging;

@com.google.protobuf.Generated
public final class ManagedCharging {
  private ManagedCharging() {}
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 31,
      /* patch= */ 1,
      /* suffix= */ "",
      ManagedCharging.class.getName());
  }
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  /**
   * <pre>
   * The reasons why the site controller may recommend no charge.
   * The site controller will only return the highest priority reason to the vehicle.
   * </pre>
   *
   * Protobuf enum {@code ManagedCharging.ChargeOnSolarNoChargeReason}
   */
  public enum ChargeOnSolarNoChargeReason
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>CHARGE_ON_SOLAR_NO_CHARGE_REASON_INVALID = 0;</code>
     */
    CHARGE_ON_SOLAR_NO_CHARGE_REASON_INVALID(0),
    /**
     * <pre>
     * The Powerwall is being prioritized over the vehicle to charge.
     * </pre>
     *
     * <code>CHARGE_ON_SOLAR_NO_CHARGE_REASON_POWERWALL_CHARGE_PRIORITY = 1;</code>
     */
    CHARGE_ON_SOLAR_NO_CHARGE_REASON_POWERWALL_CHARGE_PRIORITY(1),
    /**
     * <pre>
     * There is not enough solar for the vehicle to charge effectively.
     * </pre>
     *
     * <code>CHARGE_ON_SOLAR_NO_CHARGE_REASON_INSUFFICIENT_SOLAR = 2;</code>
     */
    CHARGE_ON_SOLAR_NO_CHARGE_REASON_INSUFFICIENT_SOLAR(2),
    /**
     * <pre>
     * The site controller is prioritizing export to the grid. This can
     * happen when the site controller is in autonomous mode and it is
     * most economical to export excess solar to the grid, or during a
     * virtual power plant event.
     * </pre>
     *
     * <code>CHARGE_ON_SOLAR_NO_CHARGE_REASON_GRID_EXPORT_PRIORITY = 3;</code>
     */
    CHARGE_ON_SOLAR_NO_CHARGE_REASON_GRID_EXPORT_PRIORITY(3),
    /**
     * <pre>
     * Another vehicle is charging on solar at this location and has priority.
     * </pre>
     *
     * <code>CHARGE_ON_SOLAR_NO_CHARGE_REASON_ALTERNATE_VEHICLE_CHARGE_PRIORITY = 4;</code>
     */
    CHARGE_ON_SOLAR_NO_CHARGE_REASON_ALTERNATE_VEHICLE_CHARGE_PRIORITY(4),
    UNRECOGNIZED(-1),
    ;

    static {
      com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
        com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
        /* major= */ 4,
        /* minor= */ 31,
        /* patch= */ 1,
        /* suffix= */ "",
        ChargeOnSolarNoChargeReason.class.getName());
    }
    /**
     * <code>CHARGE_ON_SOLAR_NO_CHARGE_REASON_INVALID = 0;</code>
     */
    public static final int CHARGE_ON_SOLAR_NO_CHARGE_REASON_INVALID_VALUE = 0;
    /**
     * <pre>
     * The Powerwall is being prioritized over the vehicle to charge.
     * </pre>
     *
     * <code>CHARGE_ON_SOLAR_NO_CHARGE_REASON_POWERWALL_CHARGE_PRIORITY = 1;</code>
     */
    public static final int CHARGE_ON_SOLAR_NO_CHARGE_REASON_POWERWALL_CHARGE_PRIORITY_VALUE = 1;
    /**
     * <pre>
     * There is not enough solar for the vehicle to charge effectively.
     * </pre>
     *
     * <code>CHARGE_ON_SOLAR_NO_CHARGE_REASON_INSUFFICIENT_SOLAR = 2;</code>
     */
    public static final int CHARGE_ON_SOLAR_NO_CHARGE_REASON_INSUFFICIENT_SOLAR_VALUE = 2;
    /**
     * <pre>
     * The site controller is prioritizing export to the grid. This can
     * happen when the site controller is in autonomous mode and it is
     * most economical to export excess solar to the grid, or during a
     * virtual power plant event.
     * </pre>
     *
     * <code>CHARGE_ON_SOLAR_NO_CHARGE_REASON_GRID_EXPORT_PRIORITY = 3;</code>
     */
    public static final int CHARGE_ON_SOLAR_NO_CHARGE_REASON_GRID_EXPORT_PRIORITY_VALUE = 3;
    /**
     * <pre>
     * Another vehicle is charging on solar at this location and has priority.
     * </pre>
     *
     * <code>CHARGE_ON_SOLAR_NO_CHARGE_REASON_ALTERNATE_VEHICLE_CHARGE_PRIORITY = 4;</code>
     */
    public static final int CHARGE_ON_SOLAR_NO_CHARGE_REASON_ALTERNATE_VEHICLE_CHARGE_PRIORITY_VALUE = 4;


    public final int getNumber() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalArgumentException(
            "Can't get the number of an unknown enum value.");
      }
      return value;
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static ChargeOnSolarNoChargeReason valueOf(int value) {
      return forNumber(value);
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     */
    public static ChargeOnSolarNoChargeReason forNumber(int value) {
      switch (value) {
        case 0: return CHARGE_ON_SOLAR_NO_CHARGE_REASON_INVALID;
        case 1: return CHARGE_ON_SOLAR_NO_CHARGE_REASON_POWERWALL_CHARGE_PRIORITY;
        case 2: return CHARGE_ON_SOLAR_NO_CHARGE_REASON_INSUFFICIENT_SOLAR;
        case 3: return CHARGE_ON_SOLAR_NO_CHARGE_REASON_GRID_EXPORT_PRIORITY;
        case 4: return CHARGE_ON_SOLAR_NO_CHARGE_REASON_ALTERNATE_VEHICLE_CHARGE_PRIORITY;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<ChargeOnSolarNoChargeReason>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        ChargeOnSolarNoChargeReason> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<ChargeOnSolarNoChargeReason>() {
            public ChargeOnSolarNoChargeReason findValueByNumber(int number) {
              return ChargeOnSolarNoChargeReason.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalStateException(
            "Can't get the descriptor of an unrecognized enum value.");
      }
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return ManagedCharging.getDescriptor().getEnumTypes().get(0);
    }

    private static final ChargeOnSolarNoChargeReason[] VALUES = values();

    public static ChargeOnSolarNoChargeReason valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      if (desc.getIndex() == -1) {
        return UNRECOGNIZED;
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private ChargeOnSolarNoChargeReason(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:ManagedCharging.ChargeOnSolarNoChargeReason)
  }


  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\026managed_charging.proto\022\017ManagedChargin" +
      "g*\307\002\n\033ChargeOnSolarNoChargeReason\022,\n(CHA" +
      "RGE_ON_SOLAR_NO_CHARGE_REASON_INVALID\020\000\022" +
      ">\n:CHARGE_ON_SOLAR_NO_CHARGE_REASON_POWE" +
      "RWALL_CHARGE_PRIORITY\020\001\0227\n3CHARGE_ON_SOL" +
      "AR_NO_CHARGE_REASON_INSUFFICIENT_SOLAR\020\002" +
      "\0229\n5CHARGE_ON_SOLAR_NO_CHARGE_REASON_GRI" +
      "D_EXPORT_PRIORITY\020\003\022F\nBCHARGE_ON_SOLAR_N" +
      "O_CHARGE_REASON_ALTERNATE_VEHICLE_CHARGE" +
      "_PRIORITY\020\004BNZLgithub.com/teslamotors/ve" +
      "hicle-command/pkg/protocol/protobuf/mana" +
      "gedchargingb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    descriptor.resolveAllFeaturesImmutable();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
